cpath      = "./engine/cservice/?.so"
lua_cpath  = "./engine/luaclib/?.so"
lualoader  = "./engine/lualib/loader.lua"
lua_path   = "./engine/lualib/?.lua;./script/lualib/?.lua"
luaservice = "./engine/service/?.lua;./script/service/?.lua"
snax       = "./script/?.lua"

thread  = 8
logger  = nil
logpath = "."
harbor  = 1
address = "127.0.0.1:2526"
master  = "127.0.0.1:2013"
start   = "server"
bootstrap  = "snlua bootstrap"
standalone = "0.0.0.0:2013"
